# Generated by Django 3.1.5 on 2021-01-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
